config/routes.rb
Quiztest::Application.routes.draw do
  devise_for :users

  resources :ideas
root :to => redirect('/ideas')

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :answer, :name, :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  with: :exception
  before_filter :authenticate_user!
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Title of this Question" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Do you have New Questions</h1>

<table>
  <tr>
    <th>Your Name</th></tr>
    <tr>
    <th>Question</th>
   <!-- this line is for answers --> <th>Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.name %></td>
    <td><%= idea.question %></td>
  <!--fecth the answers  <td><%= idea.answer %></td> -->
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<table>
	<tr>
  <th>Name:</th>
<td>  <%= @idea.name %>
</td></tr>

<tr>
  <th>Question:</th>
 <td> <%= @idea.question %></td>
</tr>

<p>
  <b>Answer:</b>
  <%= @idea.answer %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiztest</title>
  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
</head>
<body>
	<!-- devise login controls -->
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<!-- devise control -->
<div class="container">
  <%= yield %>
</div>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Idea app</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Ideas</a></li>
      </ul>
      <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </div>
  </div>
</nav>

<footer>
  <div class="container">
    Andela Project. 
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>